import type { AgentConfig } from "../config";
import { BACKEND_IMAGE, UI_IMAGE } from "../version";

// The CLI is the template engine: everything is rendered to concrete values,
// no compose ${} interpolation and no user-facing .env. AGENT_IMAGE /
// AGENT_UI_IMAGE override the image refs for local development (`:dev` builds).
export function composeYaml(config: AgentConfig): string {
  const appImage = process.env.AGENT_IMAGE ?? `${BACKEND_IMAGE}:${config.release}`;
  const uiImage = process.env.AGENT_UI_IMAGE ?? `${UI_IMAGE}:${config.uiTag}`;

  const appPorts = config.startWebUi
    ? ""
    : `\n    ports:\n      - "${config.port}:3001"`;

  const uiService = config.startWebUi
    ? `
  ui:
    image: ${uiImage}
    restart: unless-stopped
    ports:
      - "${config.port}:80"
    depends_on:
      app:
        condition: service_healthy
`
    : "";

  return `# Generated by the agent CLI — do not edit; changes are overwritten.
# Configuration lives in ../config.json (edit via \`agent config set\`).
name: agent
services:
  app:
    image: ${appImage}
    restart: unless-stopped
    env_file:
      - app.env
    # Lets URLs entered in the dashboard (e.g. an LM Studio instance running
    # on this machine) reach the host from inside the container on Linux.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - models:/models
      - files:/files
    depends_on:
      db:
        condition: service_healthy
      searxng:
        condition: service_started
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:3001/agent/health').then(r=>process.exit(r.ok?0:1),()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s${appPorts}
${uiService}
  searxng:
    image: searxng/searxng:2026.7.5-fd5eb84a3
    restart: unless-stopped
    volumes:
      - ./searxng:/etc/searxng

  db:
    image: pgvector/pgvector:pg18
    restart: unless-stopped
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: "${config.secrets.postgresPassword}"
      POSTGRES_DB: agent
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent -d agent"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  models:
  files:
`;
}

export function appEnv(config: AgentConfig): string {
  return [
    `DATABASE_URL=postgres://agent:${config.secrets.postgresPassword}@db:5432/agent`,
    `BETTER_AUTH_SECRET=${config.secrets.betterAuthSecret}`,
    `APP_ORIGIN=${config.appOrigin}`,
    `SEARXNG_URL=http://searxng:8080`,
    `TRANSFORMERS_CACHE=/models`,
    `FILES_DIR=/files`,
    `MIGRATE=on`,
    `PORT=3001`,
    "",
  ].join("\n");
}
